# Generated by Django 3.0.2 on 2020-04-04 13:14

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, validators=[django.contrib.auth.password_validation.UserAttributeSimilarityValidator, django.contrib.auth.password_validation.MinimumLengthValidator, django.contrib.auth.password_validation.CommonPasswordValidator, django.contrib.auth.password_validation.NumericPasswordValidator], verbose_name='password'),
        ),
    ]
